# Generated by Django 4.2.5 on 2023-10-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed_users', '0002_userfavoritelocation_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userfavoritelocation',
            constraint=models.UniqueConstraint(fields=('user', 'location'), name='unique_user_location'),
        ),
    ]
