# Generated by Django 4.2.5 on 2023-11-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed_location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='at_location',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
