# Generated by Django 4.2.5 on 2023-11-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed_hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='money',
        ),
        migrations.AddField(
            model_name='hotel',
            name='agoda',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_agoda',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
