# Generated by Django 4.2.5 on 2023-11-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed_hotel', '0002_remove_hotel_money_hotel_agoda_hotel_image_agoda'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image_tra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='tra',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
