# Generated by Django 4.2.5 on 2023-11-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed_hotel', '0003_hotel_image_tra_hotel_tra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='tra',
            field=models.URLField(blank=True, max_length=700),
        ),
    ]
