# Generated by Django 4.2.5 on 2023-11-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('at_location', models.CharField(blank=True, max_length=100)),
                ('googlemap', models.URLField(blank=True, max_length=500)),
                ('star', models.CharField(blank=True, max_length=100)),
                ('date', models.CharField(blank=True, max_length=20)),
                ('image', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
