# Generated by Django 4.2.5 on 2023-11-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed_res', '0002_alter_res_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='res',
            name='star',
        ),
        migrations.AddField(
            model_name='res',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
