# Generated by Django 4.2.5 on 2023-11-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed_res', '0003_remove_res_star_res_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='res',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
