# Generated by Django 4.2.5 on 2023-11-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wed_res', '0005_alter_res_at_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='res',
            name='wed',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
